config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'

  get '/prototypes/newest', to: 'prototypes#newest'
  resources :prototypes do
    resources :captured_images, only: [:create, :update, :destroy]
    resources :comments , only: [:create, :edit, :update, :destroy]
  end
  resources :tags, only: [:index,:show] # id: '/^[a-z]+$/'idを拡張してurlにタグ名で表示
  resources :users, only: [:show, :edit, :update]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype

  validates :content,presence: true
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_and_belongs_to_many :tags
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images
  accepts_nested_attributes_for :tags ,reject_if: :reject_tags_blank 
  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end
  def reject_tags_blank(attributed)
    attributed['name'].blank?
  end
  # after_create do
  #   prototype = Prototype.find_by(id:self.id)
  #   binding.pry
  #   #ここにどうやってフォームのタグのデータもってくるかだ
  #   #sometags = self.class.scan("tag")
  #   #sometags.uniq.map do |onetag|
  #   tag = Tag.find_or_create_by(name: onetag)
  #   prototype.tags << tag
  #   #end
  # end

  # before_update do
  #   prototype = Prototype.find_by(id: self.id)
  #   prototype.tags.clear
  #   sometags = self.class.scan("tag")
  #   sometags.uniq.map do |onetag|
  #     tag = Tag.find_or_create_by(name: onetag)
  #     prototype.tags << tag
  #   end
  # end

end

app/models/prototype_like.rb
class PrototypeLike < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :user
end

app/models/prototypes_tag.rb
class PrototypesTag < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :prototypes
end

app/models/tag_prototype.rb
class TagPrototype < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :prototype_likes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to prototype_path(params[:prototype_id])}
        format.json
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to prototype_path(params[:prototype_id]) }
        format.json {render json: @comment}
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user.id == current_user.id
      if @comment.destroy
        respond_to do |format|
          format.html { redirect_to prototype_path(params[:prototype_id]) }
          format.json {render json: @comment}
        end
      end

    end
  end


  private

    def comment_params
      params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
    end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:show, :destroy, :edit, :update]

  def index
    #現状Like数でのソートになっていません。Like機能追加後に修正します。
    @prototypes = Prototype.page(params[:page]).per(8).order("created_at ASC")
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
    3.times do
      @prototype.tags.build
    end
    #@tag1 = Tag.new
    #@tag2 = Tag.new
    #@tag3 = Tag.new
    #@tags = [@tag1,@tag2,@tag3]
  end

  def create
    @prototype = Prototype.new(prototype_params)
    n =[]
    @prototype.tags.each do |t|
      tag = Tag.find_by(name: t.name)
      unless tag == nil
        n << tag
      else
        n << t
      end
    end
    @prototype.tags = []
    n.each do |w|
      @prototype.tags << w
    end


    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      render :new
    end
  end

  def show

    @tags = Prototype.find(params[:id]).tags
    @comment = Comment.new
    @comments = @prototype.comments.order(created_at: :DESC).includes(:user)
  end

  def edit
    PrototypesTag.where(prototype_id:@prototype.id).destroy_all
    3.times do
      @prototype.tags.build
    end
  end

  def update
 
    n =[]
    @prototype.tags.each do |t|
      tag = Tag.find_by(name: t.name)
      unless tag == nil
        n << tag
      else
        n << t
      end
    end
    @prototype.tags = []
    n.each do |w|
      @prototype.tags << w
    end
    if @prototype.update(prototype_update_params)
      redirect_to root_path, alert: 'Prototype was successfully Update'
    else
      render :edit
    end

  end
  def destroy
    @prototype.destroy
    redirect_to :root, alert: 'Prototype was successfully deleted'
  end

  def newest
    @prototypes = Prototype.page(params[:page]).per(8).order("created_at DESC")
  end


  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status],
      tags_attributes: [:name]
    )
  end

  def prototype_update_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status, :id],
      tags_attributes: [:name,:id]
    )
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
  def show
   @prototypes = Tag.find(params[:id]).prototypes.page(params[:page]).per(8).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def set_avater(ins = "none")
    if ins != "none"
      if ins.user[:avatar].nil?
        return "/assets/ava.png"
      else
        return ins.user.avatar.thumb.url
      end
    else
      if @user[:avatar].nil?
        return "/assets/ava.png"
      else
        return @user.avatar.thumb.url
      end
    end
  end

end

app/views/comments/_comment.html.haml
= form_for [@prototype, comment],html: {class:"comment"} do |f|
  .proto-comment--comments--comment
    .proto-comment--comments--comment__avater
      = image_tag(set_avater(comment), alt: "profile", class: "user-avater", style: "width: 64px; height: 64px;")
    .proto-comment--comments--comment--right
      .proto-comment--comments--comment--right__user-name
        = comment.user.name
        -if user_signed_in? && current_user.id == comment.user.id
          .btn.btn-default.delete_btn
            Delete
          .btn.btn-default.edit_btn
            edit
          = f.submit "Update", class: "btn btn-default submit_btn"

      .proto-comment--comments--comment--right__text
        = comment.content
      = f.text_field :content, value: comment.content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    %script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
    %script src="prototype_like.js"
  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == prototype.user_id
    .dropdown.drop_menu_location
      %button#dropdownMenu.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button"}
        Action
      %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
        %li
          = link_to "Delete", prototype_path(prototype), method: :delete
        %li
          = link_to "EDIT", edit_prototype_path(prototype)
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload.main_image_uploader
            = image_tag(@prototype.set_main_thumbnail, style: "width: 100%; height: 100%;", class: "main_image")
            = f.fields_for :captured_images  do |image|
              - if image.index == 0
                = image.file_field :content, value: image.object.content
                = image.hidden_field :status, value: "main"

        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group.sub_image_uploder
            = f.fields_for :captured_images do |image|
              - if image.object != @prototype.captured_images[0]
                %li.list-group-item.col-md-4.edit_subs
                  .image-upload
                    = image_tag(image.object.content, style: "width: 100%; height: 100%;", class: "sub_image")
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"

      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
          .col-md-12
          %h4 Tag List
          - @prototype.tags.each do |tag|
            .col-md-3
              = f.fields_for :tags, tag do |tag_field|
                = tag_field.text_field :name, placeholder: "New Tag"

      .row.text-center.proto-btn
        = f.submit "UPDATE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes/newest"

      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"


.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate(@prototypes)
  / %ul.pagination
  /   %li.disabled
  /     %a{"aria-label": "Previous", href: "#"}
  /       %span{"aria-hidden": "true"} «
  /   %li.active
  /     %a{href: "#"}
  /       1
  /       %span.sr-only (current)
  /   %li
  /     %a{href: "#"} 2
  /   %li
  /     %a{href: "#"} 3
  /   %li
  /     %a{href: "#"} 4
  /   %li
  /     %a{href: "#"} 5
  /   %li
  /     %a{"aria-label": "Next", href: "#"}
  /       %span{"aria-hidden": "true"} »

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload.main_image_uploader
            = f.fields_for :captured_images do |image|
              = image_tag(src= "", style: "width: 100%; height: 100%;", class: "main_image")
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group.sub_image_uploder
            - 3.times do |i|
              - i == 2 ? set_style = "display: none;" : set_style = ""
              %li.list-group-item.col-md-4{style: set_style}
                .image-upload
                  = f.fields_for :captured_images do |image|
                    = image_tag(src= "", style: "width: 100%; height: 100%;", class: "sub_image")
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
            %li.add_sub.list-group-item.col-md-4
              %div
                追加したいな

      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          - @prototype.tags.each do |tag|
            .col-md-3
              = f.fields_for :tags, tag do |tag_field|
                = tag_field.text_field :name, placeholder: "New Tag"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/newest.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes/newest"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"


.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate(@prototypes)
  / %ul.pagination
  /   %li.disabled
  /     %a{"aria-label": "Previous", href: "#"}
  /       %span{"aria-hidden": "true"} «
  /   %li.active
  /     %a{href: "#"}
  /       1
  /       %span.sr-only (current)
  /   %li
  /     %a{href: "#"} 2
  /   %li
  /     %a{href: "#"} 3
  /   %li
  /     %a{href: "#"} 4
  /   %li
  /     %a{href: "#"} 5
  /   %li
  /     %a{"aria-label": "Next", href: "#"}
  /       %span{"aria-hidden": "true"} »

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(set_avater(@prototype), alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @tags.each do |tag|
          %li
            = link_to tag.name ,tag_path(tag.id), class: "btn btn-default"
  .row.proto-comment
    .proto-comment--head.comment-head
      Comments (
      %span#comment_count
        = @comments.count
      )
    .proto-comment--comments
      = render partial: './comments/comment', collection: @comments


    .proto-comment--footer
      .proto-comment--footer__head.comment-head
        Write a comment
      .proto-comment--footer__form
        = form_for [@prototype, @comment] do |f|
          .proto-comment--footer__form__input
            = f.text_area :content, placeholder: 'Your Comment'
          - if user_signed_in?
            = f.submit "COMMENT", class: "proto-comment--footer__form__submit btn btn-primary"
          - else
            = link_to "COMMENT", new_user_session_path, class: "proto-comment--footer__form__submit btn btn-primary"

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2
        Tags-list
        %ul
          - @tags.each do |tag|
            %li.list-box
              = link_to tag.name ,tag_path(tag.id), class: "btn btn-default "

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes/newest"
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"


.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate(@prototypes)

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(set_avater(), alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes